#CREATE A PYTHON PROGRAM THAT ASKS THE USER HOW FAR THEY WANT TO TRAVEL.IF THEY WANT TO TRAVEL LESS THAN THREE MILES TELL THEM TO RIDE BYCYCLES.IF THEY WANT TO TRAVEL MORE THAN THREE BUT LESS THAN 300 KM TELL THEM TO RIDE MOTORCYCLE.FOR MORE THAN 300 TELL THEM TO DRIVE SUPERCAR

distance=int(input("Enter the distance to be travelled: "))
if distance<3:
    print("USE BYCYCLE")
elif distance>3 and distance<300:
    print("USE MOTORCYCLE")
else:
    print("USE SUPERCAR")
